name: Run Licco Tests using Conda

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    services:
      mongo:
        image: "mongo:8.0.0"
        ports: 
          - 27017:27017
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.7'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #
        # These are just stylistic issues, which aren't really important
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda run python -m pytest tests
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install Frontend dependencies
      working-directory: './react'
      run: npm install
    - name: Run Frontend Tests
      working-directory: './react'
      run: npm run test
